const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/passp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true});try{const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const url=process.env.PREVIEW_URL;await p.goto(url);await p.waitForFunction(()=>document.querySelector('#headline').textContent.includes('%'));assert.equal(await p.locator('#load-error').isVisible(),false);
 const initial=await p.locator('#pool-count').innerText();await p.selectOption('#income','75000');assert.notEqual(await p.locator('#pool-count').innerText(),initial);await p.click('#save');await p.selectOption('#sex','Males');await p.click('#save');assert.equal(await p.locator('.compare-card').count(),2);
 for(const id of ['orientation','bmi','education','ethnicity','heightMin','heightMax']) assert.equal(await p.locator('#'+id).isVisible(),true);assert.equal(await p.locator('#heightMin').isDisabled(),false);assert.equal(await p.locator('#education option').count(),8);const cmBefore=await p.locator('#heightMin').inputValue();await p.selectOption('#height-unit','ft');await p.selectOption('#height-unit','cm');assert.equal(await p.locator('#heightMin').inputValue(),cmBefore);await p.selectOption('#height-unit','ft');await p.fill('#min-feet','6');await p.fill('#min-inches','0');assert.equal(Number(await p.locator('#heightMin').inputValue()),182.88);await p.fill('#min-inches','12');assert.equal(await p.locator('#input-error').isVisible(),true);await p.fill('#min-inches','0');await p.selectOption('#height-unit','cm');await p.fill('#heightMin','180');await p.fill('#heightMax','210');assert.match(await p.locator('#assumptions').textContent(),/MODELLING ASSUMPTION/);
 await p.selectOption('#bmi','1');await p.selectOption('#education','level4');await p.selectOption('#ethnicity','Asian');await p.selectOption('#orientation','straightBi');
 const dp=p.waitForEvent('download');await p.click('#download');const d=await dp;const payload=JSON.parse(await fs.readFile(await d.path(),'utf8'));assert.equal(payload.state.income,75000);assert.equal(payload.state.height,true);assert.equal(payload.sources.length,7);assert.ok(payload.notes.length>5);
 await p.click('#share-link');await p.reload();await p.waitForFunction(()=>document.querySelector('#income').value==='75000');assert.equal(await p.locator('input[type=checkbox]').count(),0);
 await p.fill('#min','70');await p.fill('#max','25');assert.equal(await p.locator('#input-error').isVisible(),true);assert.equal(await p.locator('#download').isDisabled(),true);await p.click('#reset');
 await p.screenshot({path:path.join(__dirname,'../dating-desktop-qa.png'),fullPage:true});for(const width of [390,430,768]){await p.setViewportSize({width,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(width===390)await p.screenshot({path:path.join(__dirname,'../dating-mobile-qa.png'),fullPage:true});}
 for(const file of ['hmrc-2023-24.ods','qualifications-2021.xlsx']) assert.equal((await p.request.get(url+'/sources/'+file)).status(),200);await p.getByRole('link',{name:'Sources',exact:true}).click();await p.waitForSelector('#library article');assert.equal(await p.locator('#library article').count(),7);await p.getByRole('link',{name:'Data explorer',exact:true}).click();await p.waitForSelector('#mode');assert.equal(await p.locator('#load-error').isVisible(),false);assert.deepEqual(errors,[]);console.log('Dating browser QA passed: filters, comparison, height opt-in, dedicated sources page, source export, URL reload, invalid ages, desktop/mobile overflow and explorer navigation.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
